version: '3.7'

services:
  database:
    image: postgres:11.2
    restart: always
    env_file:
      - dev-vars.env
    ports:
    - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn -w 3 -k gevent -b 0.0.0.0:5000 app:app
    env_file:
      - dev-vars.env
    volumes:
      - ./web:/home/worker
      - ./utils:/home/worker/utils
    ports:
      - "5000:5000"
    depends_on:
      - database
    restart: always

  worker:
    build: .
    command: ./worker_entrypoint.sh
    volumes:
      - ./worker:/home/worker
      - ./utils:/home/worker/utils
      - ./tests:/home/worker/tests
    depends_on:
      - database
    env_file:
      - dev-vars.env
    restart: always
